### PR TITLE
Remove special casing for NoTier when sorting

### PR DESCRIPTION
**Pull request by SSM240**
Since we have more control over tier sorting now, we don't need `NoTier` to be a special case anymore, so I added it to the set of tiers that can be sorted normally, defaulting to being at the end for both presets. There is still a _little_ special casing because apparently it's just not part of `RoR2.ContentManagement.ContentManager.itemTierDefs`, so I have to add it manually if it's missing from the settings.

This fixes the same bug as in #89, where Consumed Regenerating Scrap breaks tier sorting because it's a scrap item with no tier, but in a cleaner way.

### CODE REVIEW

**Comment by SSM240** [comment]
sorry to bump, even if you don't have time to look at all my PRs can you at least look at this one specifically? It fixes a bug I accidentally introduced in the last update and I feel bad leaving that in there for so long.

**Comment by ToastedOven** [comment]
Thanks for the bump, I actually completely forgot to come back to all this, let me get on it now. Sorry about that!

**Comment by ToastedOven** [comment]
Honestly, I'm just gonna give you write permissions. Please don't feel obligated to do anything more than you have, it's just that you write fine code, so I'm trusting you with this so you don't have to wait for my forgetful ass to remember to review your PRs

**Comment by SSM240** [comment]
oh lol alright, I don't know if I'll even use it because I'm afraid of messing things up on my own, but thanks either way 😅

**Pull request merged**
